on:
  pull_request_target

jobs:
  build:
    name: Add Size Label to PR
    runs-on: ubuntu-latest
    steps:
      - name: Add Size Label to PR
        uses: WizardOhio24/label-pr-size-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          size-label-color: '10, size: x-small, ffaf65 | 50, size: small, ff9e58 | 250, size: medium, ff9654 | 500, size: large, ff905d | 100000, size: x-large, ff905d'
