name: Add/Remove Labels

on:
  pull_request_target:
    types: [opened]

jobs:
  add_new_contributor_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add new contributor label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            async function addNewLabel() {
              const creator = context.payload.sender.login;
              const opts = github.rest.issues.listForRepo.endpoint.merge({
                ...context.issue,
                creator,
                state: 'all',
              });
              
              const issues = await github.paginate(opts);

              // Check if the creator is already a contributor to any issue.
              for (const issue of issues) {
                if (issue.number === context.issue.number) {
                  continue;
                }

                if (issue.pull_request && issue.user.login === creator) {
                  return;
                }
              }

              // Add the label if the creator is a new contributor.
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['new contributor'],
              });
            }

            addNewLabel();
