on: push
name: New workflow
jobs:
  helloMonasWorld:
    name: Hello Monas World
    runs-on: ubuntu-latest
    steps:
    - name: Hello Monas World
      uses: ./
      env:
        MY_NAME: Hi, I'm Mona!
      with:
        args: '"Hello world, I''m $MY_NAME!"'
